const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const { version } = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf-8"));
const out = `// Generated by scripts/gen-version.cjs from package.json. Do not edit manually.\nexport const VERSION = ${JSON.stringify(version)};\n`;
const file = path.join(root, "src", "version.ts");
if (!fs.existsSync(file) || fs.readFileSync(file, "utf-8") !== out) fs.writeFileSync(file, out);
